// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFeatureFlags is an autogenerated mock type for the FeatureFlags type
type MockFeatureFlags struct {
	mock.Mock
}

type MockFeatureFlags_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureFlags) EXPECT() *MockFeatureFlags_Expecter {
	return &MockFeatureFlags_Expecter{mock: &_m.Mock}
}

// GetFloat provides a mock function with given fields: ctx, flag, defaultValue
func (_m *MockFeatureFlags) GetFloat(ctx context.Context, flag string, defaultValue float64) float64 {
	ret := _m.Called(ctx, flag, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for GetFloat")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) float64); ok {
		r0 = rf(ctx, flag, defaultValue)
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockFeatureFlags_GetFloat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFloat'
type MockFeatureFlags_GetFloat_Call struct {
	*mock.Call
}

// GetFloat is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue float64
func (_e *MockFeatureFlags_Expecter) GetFloat(ctx interface{}, flag interface{}, defaultValue interface{}) *MockFeatureFlags_GetFloat_Call {
	return &MockFeatureFlags_GetFloat_Call{Call: _e.mock.On("GetFloat", ctx, flag, defaultValue)}
}

func (_c *MockFeatureFlags_GetFloat_Call) Run(run func(ctx context.Context, flag string, defaultValue float64)) *MockFeatureFlags_GetFloat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64))
	})
	return _c
}

func (_c *MockFeatureFlags_GetFloat_Call) Return(_a0 float64) *MockFeatureFlags_GetFloat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeatureFlags_GetFloat_Call) RunAndReturn(run func(context.Context, string, float64) float64) *MockFeatureFlags_GetFloat_Call {
	_c.Call.Return(run)
	return _c
}

// GetInt provides a mock function with given fields: ctx, flag, defaultValue
func (_m *MockFeatureFlags) GetInt(ctx context.Context, flag string, defaultValue int) int {
	ret := _m.Called(ctx, flag, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for GetInt")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, string, int) int); ok {
		r0 = rf(ctx, flag, defaultValue)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockFeatureFlags_GetInt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInt'
type MockFeatureFlags_GetInt_Call struct {
	*mock.Call
}

// GetInt is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue int
func (_e *MockFeatureFlags_Expecter) GetInt(ctx interface{}, flag interface{}, defaultValue interface{}) *MockFeatureFlags_GetInt_Call {
	return &MockFeatureFlags_GetInt_Call{Call: _e.mock.On("GetInt", ctx, flag, defaultValue)}
}

func (_c *MockFeatureFlags_GetInt_Call) Run(run func(ctx context.Context, flag string, defaultValue int)) *MockFeatureFlags_GetInt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockFeatureFlags_GetInt_Call) Return(_a0 int) *MockFeatureFlags_GetInt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeatureFlags_GetInt_Call) RunAndReturn(run func(context.Context, string, int) int) *MockFeatureFlags_GetInt_Call {
	_c.Call.Return(run)
	return _c
}

// GetJSON provides a mock function with given fields: ctx, flag, target
func (_m *MockFeatureFlags) GetJSON(ctx context.Context, flag string, target interface{}) error {
	ret := _m.Called(ctx, flag, target)

	if len(ret) == 0 {
		panic("no return value specified for GetJSON")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, flag, target)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFeatureFlags_GetJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJSON'
type MockFeatureFlags_GetJSON_Call struct {
	*mock.Call
}

// GetJSON is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - target interface{}
func (_e *MockFeatureFlags_Expecter) GetJSON(ctx interface{}, flag interface{}, target interface{}) *MockFeatureFlags_GetJSON_Call {
	return &MockFeatureFlags_GetJSON_Call{Call: _e.mock.On("GetJSON", ctx, flag, target)}
}

func (_c *MockFeatureFlags_GetJSON_Call) Run(run func(ctx context.Context, flag string, target interface{})) *MockFeatureFlags_GetJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockFeatureFlags_GetJSON_Call) Return(_a0 error) *MockFeatureFlags_GetJSON_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeatureFlags_GetJSON_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *MockFeatureFlags_GetJSON_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function with given fields: ctx, flag, defaultValue
func (_m *MockFeatureFlags) GetString(ctx context.Context, flag string, defaultValue string) string {
	ret := _m.Called(ctx, flag, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, flag, defaultValue)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFeatureFlags_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockFeatureFlags_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue string
func (_e *MockFeatureFlags_Expecter) GetString(ctx interface{}, flag interface{}, defaultValue interface{}) *MockFeatureFlags_GetString_Call {
	return &MockFeatureFlags_GetString_Call{Call: _e.mock.On("GetString", ctx, flag, defaultValue)}
}

func (_c *MockFeatureFlags_GetString_Call) Run(run func(ctx context.Context, flag string, defaultValue string)) *MockFeatureFlags_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockFeatureFlags_GetString_Call) Return(_a0 string) *MockFeatureFlags_GetString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeatureFlags_GetString_Call) RunAndReturn(run func(context.Context, string, string) string) *MockFeatureFlags_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function with given fields: ctx, flag, defaultValue
func (_m *MockFeatureFlags) IsEnabled(ctx context.Context, flag string, defaultValue bool) bool {
	ret := _m.Called(ctx, flag, defaultValue)

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) bool); ok {
		r0 = rf(ctx, flag, defaultValue)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockFeatureFlags_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockFeatureFlags_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - flag string
//   - defaultValue bool
func (_e *MockFeatureFlags_Expecter) IsEnabled(ctx interface{}, flag interface{}, defaultValue interface{}) *MockFeatureFlags_IsEnabled_Call {
	return &MockFeatureFlags_IsEnabled_Call{Call: _e.mock.On("IsEnabled", ctx, flag, defaultValue)}
}

func (_c *MockFeatureFlags_IsEnabled_Call) Run(run func(ctx context.Context, flag string, defaultValue bool)) *MockFeatureFlags_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *MockFeatureFlags_IsEnabled_Call) Return(_a0 bool) *MockFeatureFlags_IsEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFeatureFlags_IsEnabled_Call) RunAndReturn(run func(context.Context, string, bool) bool) *MockFeatureFlags_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFeatureFlags creates a new instance of MockFeatureFlags. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureFlags(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockFeatureFlags {
	mock := &MockFeatureFlags{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
