// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/jsamuelsen/go-service-template/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockQuoteClient is an autogenerated mock type for the QuoteClient type
type MockQuoteClient struct {
	mock.Mock
}

type MockQuoteClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuoteClient) EXPECT() *MockQuoteClient_Expecter {
	return &MockQuoteClient_Expecter{mock: &_m.Mock}
}

// GetQuoteByID provides a mock function with given fields: ctx, id
func (_m *MockQuoteClient) GetQuoteByID(ctx context.Context, id string) (*domain.Quote, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQuoteByID")
	}

	var r0 *domain.Quote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Quote, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Quote); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Quote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuoteClient_GetQuoteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuoteByID'
type MockQuoteClient_GetQuoteByID_Call struct {
	*mock.Call
}

// GetQuoteByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockQuoteClient_Expecter) GetQuoteByID(ctx interface{}, id interface{}) *MockQuoteClient_GetQuoteByID_Call {
	return &MockQuoteClient_GetQuoteByID_Call{Call: _e.mock.On("GetQuoteByID", ctx, id)}
}

func (_c *MockQuoteClient_GetQuoteByID_Call) Run(run func(ctx context.Context, id string)) *MockQuoteClient_GetQuoteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockQuoteClient_GetQuoteByID_Call) Return(_a0 *domain.Quote, _a1 error) *MockQuoteClient_GetQuoteByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuoteClient_GetQuoteByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Quote, error)) *MockQuoteClient_GetQuoteByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomQuote provides a mock function with given fields: ctx
func (_m *MockQuoteClient) GetRandomQuote(ctx context.Context) (*domain.Quote, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomQuote")
	}

	var r0 *domain.Quote
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Quote, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Quote); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Quote)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuoteClient_GetRandomQuote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomQuote'
type MockQuoteClient_GetRandomQuote_Call struct {
	*mock.Call
}

// GetRandomQuote is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuoteClient_Expecter) GetRandomQuote(ctx interface{}) *MockQuoteClient_GetRandomQuote_Call {
	return &MockQuoteClient_GetRandomQuote_Call{Call: _e.mock.On("GetRandomQuote", ctx)}
}

func (_c *MockQuoteClient_GetRandomQuote_Call) Run(run func(ctx context.Context)) *MockQuoteClient_GetRandomQuote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuoteClient_GetRandomQuote_Call) Return(_a0 *domain.Quote, _a1 error) *MockQuoteClient_GetRandomQuote_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuoteClient_GetRandomQuote_Call) RunAndReturn(run func(context.Context) (*domain.Quote, error)) *MockQuoteClient_GetRandomQuote_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuoteClient creates a new instance of MockQuoteClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuoteClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockQuoteClient {
	mock := &MockQuoteClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
