// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/jsamuelsen/go-service-template/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockExampleClient is an autogenerated mock type for the ExampleClient type
type MockExampleClient struct {
	mock.Mock
}

type MockExampleClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExampleClient) EXPECT() *MockExampleClient_Expecter {
	return &MockExampleClient_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx, id
func (_m *MockExampleClient) Fetch(ctx context.Context, id string) (*ports.ExampleData, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *ports.ExampleData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ports.ExampleData, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.ExampleData); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.ExampleData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExampleClient_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockExampleClient_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockExampleClient_Expecter) Fetch(ctx interface{}, id interface{}) *MockExampleClient_Fetch_Call {
	return &MockExampleClient_Fetch_Call{Call: _e.mock.On("Fetch", ctx, id)}
}

func (_c *MockExampleClient_Fetch_Call) Run(run func(ctx context.Context, id string)) *MockExampleClient_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExampleClient_Fetch_Call) Return(_a0 *ports.ExampleData, _a1 error) *MockExampleClient_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExampleClient_Fetch_Call) RunAndReturn(run func(context.Context, string) (*ports.ExampleData, error)) *MockExampleClient_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExampleClient creates a new instance of MockExampleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExampleClient(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockExampleClient {
	mock := &MockExampleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
