// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	ports "github.com/jsamuelsen/go-service-template/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// MockExampleRepository is an autogenerated mock type for the ExampleRepository type
type MockExampleRepository struct {
	mock.Mock
}

type MockExampleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExampleRepository) EXPECT() *MockExampleRepository_Expecter {
	return &MockExampleRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockExampleRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExampleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExampleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockExampleRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockExampleRepository_Delete_Call {
	return &MockExampleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockExampleRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockExampleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExampleRepository_Delete_Call) Return(_a0 error) *MockExampleRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExampleRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockExampleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockExampleRepository) GetByID(ctx context.Context, id string) (*ports.ExampleEntity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *ports.ExampleEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ports.ExampleEntity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ports.ExampleEntity); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.ExampleEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockExampleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockExampleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockExampleRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockExampleRepository_GetByID_Call {
	return &MockExampleRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockExampleRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockExampleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockExampleRepository_GetByID_Call) Return(_a0 *ports.ExampleEntity, _a1 error) *MockExampleRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockExampleRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*ports.ExampleEntity, error)) *MockExampleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, entity
func (_m *MockExampleRepository) Save(ctx context.Context, entity *ports.ExampleEntity) error {
	ret := _m.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *ports.ExampleEntity) error); ok {
		r0 = rf(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockExampleRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockExampleRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *ports.ExampleEntity
func (_e *MockExampleRepository_Expecter) Save(ctx interface{}, entity interface{}) *MockExampleRepository_Save_Call {
	return &MockExampleRepository_Save_Call{Call: _e.mock.On("Save", ctx, entity)}
}

func (_c *MockExampleRepository_Save_Call) Run(run func(ctx context.Context, entity *ports.ExampleEntity)) *MockExampleRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ports.ExampleEntity))
	})
	return _c
}

func (_c *MockExampleRepository_Save_Call) Return(_a0 error) *MockExampleRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockExampleRepository_Save_Call) RunAndReturn(run func(context.Context, *ports.ExampleEntity) error) *MockExampleRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockExampleRepository creates a new instance of MockExampleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExampleRepository(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockExampleRepository {
	mock := &MockExampleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
