# golangci-lint configuration for enterprise-grade Go projects
# Run with: golangci-lint run ./...

version: "2"

run:
  concurrency: 4
  timeout: 5m
  tests: true

linters:
  default: all
  disable:
    # Overly strict or noisy linters
    - wsl # Too strict about whitespace
    - nlreturn # Too strict about newlines
    - varnamelen # Too strict about variable naming length
    - ireturn # Too strict about interface returns
    - gochecknoglobals # Globals are sometimes necessary
    - gochecknoinits # Inits are sometimes necessary
    - exhaustruct # Often too noisy - not all struct fields need initialization
    - nonamedreturns # Named returns are fine when used appropriately
    - testpackage # Forces black-box testing, not always desired
    - depguard # Requires specific configuration per-project

  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - net/http.ResponseWriter.Write
        - net/http.Response.Body.Close
        - io.Closer.Close

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    dupl:
      threshold: 100

    lll:
      line-length: 120

    misspell:
      locale: US

    revive:
      severity: warning

    staticcheck:
      checks:
        - all

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/jsamuelsen/go-service-template

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Relax linters for test files
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - goconst
        - gocyclo
        - gocognit
        - gocritic
        - gosec

    # Common patterns that are safe to ignore
    - linters:
        - errcheck
      text: "Error return value of .*Write.* is not checked"

    - linters:
        - govet
      text: 'shadow: declaration of "err"'
