# golangci-lint configuration for enterprise-grade Go projects
# Run with: golangci-lint run ./...

version: "2"

run:
  concurrency: 4
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    # Core quality
    - errcheck # Check for unchecked errors
    - govet # Go's built-in static analyzer
    - staticcheck # Advanced static analysis (includes gosimple)
    - unused # Find unused code

    # Security
    - gosec # Security vulnerability scanner

    # Style
    - gocritic # Opinionated code suggestions
    - revive # Fast, configurable linter (replaces golint)

    # Complexity & structure
    - gocyclo # Cyclomatic complexity
    - gocognit # Cognitive complexity
    - nestif # Nested if complexity
    - dupl # Code duplication
    - mnd # Magic number detector

    # Test quality
    - thelper # Checks t.Helper() usage in test helpers
    - tparallel # Checks t.Parallel() usage in tests
    - testifylint # Testify best practices

  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - net/http.ResponseWriter.Write
        - net/http.Response.Body.Close
        - io.Closer.Close

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

    revive:
      severity: error

    staticcheck:
      checks:
        - all

    gocyclo:
      min-complexity: 15

    gocognit:
      min-complexity: 20

    nestif:
      min-complexity: 5

    dupl:
      threshold: 100

    testifylint:
      enable-all: true

  exclusions:
    rules:
      # Relax linters for test files
      - path: _test\.go
        linters:
          - gocritic
          - gosec
          - dupl
          - mnd

      # Test-only linters — exclude from non-test files
      - path-except: _test\.go
        linters:
          - thelper
          - tparallel
          - testifylint

      # Common patterns that are safe to ignore
      - linters:
          - errcheck
        text: "Error return value of .*Write.* is not checked"

formatters:
  enable:
    - goimports
    - gofumpt

  settings:
    goimports:
      local-prefixes:
        - github.com/jsamuelsen/go-service-template

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
