# octocov configuration
# https://github.com/k1LoW/octocov

coverage:
  # Path to the Go coverage profile
  paths:
    - coverage.out
  badge:
    path: badge.svg

# Code-to-test ratio metrics
codeToTestRatio:
  code:
    - "**/*.go"
    - "!**/*_test.go"
    - "!**/mock_*.go"
    - "!**/mocks/**"
  test:
    - "**/*_test.go"

# Add comment to pull requests with coverage report
comment:
  enable: true
  if: is_pull_request

# Add to GitHub Actions job summary
summary:
  enable: true
  if: true

# Diff coverage for PRs - show coverage of changed lines
diff:
  enable: true
  if: is_pull_request

# Coverage badge is pushed to the 'octocov' branch by CI workflow steps
# (octocov's built-in push doesn't support pushing to a different branch)
# Badge URL: https://raw.githubusercontent.com/{owner}/{repo}/octocov/badge.svg
