version: "3"

vars:
  BINARY_NAME: service
  MAIN_PKG: ./cmd/service
  COVERAGE_FILE: coverage.out
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  LDFLAGS: -s -w -X main.version={{.VERSION}} -X main.commit={{.GIT_COMMIT}} -X main.buildTime={{.BUILD_TIME}}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ─────────────────────────────────────────────────────────────
  # Setup & Development
  # ─────────────────────────────────────────────────────────────

  setup:
    desc: "[Setup] Install all development dependencies"
    cmds:
      - go mod download
      - go tool lefthook install
      - echo "Setup complete. All tools available via 'go tool'. Git hooks installed."

  run:
    desc: "[Dev] Run the service locally with hot reload"
    cmds:
      - go tool air -c .air.toml || go run {{.MAIN_PKG}}

  generate:
    desc: "[Dev] Run go generate (mocks, etc.)"
    cmds:
      - go generate ./...
      - go tool mockery

  # ─────────────────────────────────────────────────────────────
  # Build
  # ─────────────────────────────────────────────────────────────

  build:
    desc: "[Build] Build production binary with version info"
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}} {{.MAIN_PKG}}

  clean:
    desc: "[Build] Clean build artifacts"
    cmds:
      - rm -rf bin/
      - rm -f {{.COVERAGE_FILE}} coverage.html

  # ─────────────────────────────────────────────────────────────
  # Code Quality
  # ─────────────────────────────────────────────────────────────

  fmt:
    desc: "[Quality] Format all Go code"
    cmds:
      - go tool gofumpt -w .

  lint:
    desc: "[Quality] Run golangci-lint"
    cmds:
      - go tool golangci-lint run --timeout 5m ./...

  vuln:
    desc: "[Quality] Run govulncheck"
    cmds:
      - go tool govulncheck ./...

  # ─────────────────────────────────────────────────────────────
  # Testing
  # ─────────────────────────────────────────────────────────────

  test:
    desc: "[Test] Run unit tests"
    cmds:
      - go test -race -v ./...

  test:integration:
    desc: "[Test] Run GoDog integration tests"
    dir: test/integration
    cmds:
      - go tool godog run --format pretty ../features/

  test:e2e:
    desc: "[Test] Run full E2E test suite"
    cmds:
      - task: test
      - task: test:integration

  test:benchmark:
    desc: "[Test] Run Go benchmarks"
    cmds:
      - go test -bench=. -benchmem ./test/benchmark/...

  test:load:
    desc: "[Test] Run k6 load tests"
    cmds:
      - k6 run test/load/k6/health.js

  coverage:
    desc: "[Test] Generate test coverage report"
    cmds:
      - go test -race -coverprofile={{.COVERAGE_FILE}} -covermode=atomic ./...
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - go tool cover -func={{.COVERAGE_FILE}}

  # ─────────────────────────────────────────────────────────────
  # CI/CD
  # ─────────────────────────────────────────────────────────────

  ci:
    desc: "[CI] Run full CI pipeline locally"
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: coverage
      - task: vuln

  # ─────────────────────────────────────────────────────────────
  # Docker
  # ─────────────────────────────────────────────────────────────

  docker:build:
    desc: "[Docker] Build Docker image"
    cmds:
      - docker build -t {{.BINARY_NAME}}:{{.VERSION}} --build-arg VERSION={{.VERSION}} --build-arg GIT_COMMIT={{.GIT_COMMIT}} --build-arg BUILD_TIME={{.BUILD_TIME}} .

  docker:run:
    desc: "[Docker] Run Docker container locally"
    cmds:
      - docker run --rm -p 8080:8080 {{.BINARY_NAME}}:{{.VERSION}}

  # ─────────────────────────────────────────────────────────────
  # OpenAPI
  # ─────────────────────────────────────────────────────────────

  openapi:validate:
    desc: "[OpenAPI] Validate OpenAPI spec"
    cmds:
      - go tool vacuum lint -r .spectral.yaml api/openapi.yaml

  openapi:diff:
    desc: "[OpenAPI] Check for OpenAPI drift"
    cmds:
      - cmd: echo "TODO Implement OpenAPI drift detection"
