version: "3"

vars:
  BINARY_NAME: service
  MAIN_PKG: ./cmd/service
  COVERAGE_FILE: coverage.out
  TEST_FORMAT: testdox # default format, override with: task test TEST_FORMAT=dots
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  LDFLAGS: -s -w -X main.version={{.VERSION}} -X main.commit={{.GIT_COMMIT}} -X main.buildTime={{.BUILD_TIME}}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ─────────────────────────────────────────────────────────────
  # Setup & Development
  # ─────────────────────────────────────────────────────────────

  setup:
    desc: "[Setup] Install all development dependencies"
    cmds:
      - go mod download
      - go tool lefthook install
      - task: setup:k6
      - echo "Setup complete. All tools available via 'go tool'. Git hooks installed."

  setup:k6:
    desc: "[Setup] Install k6 load testing tool"
    status:
      - command -v k6
    cmds:
      - cmd: |
          if command -v brew &> /dev/null; then
            brew install k6
          elif command -v apt-get &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y k6
          elif command -v choco &> /dev/null; then
            choco install k6
          else
            echo "Please install k6 manually: https://grafana.com/docs/k6/latest/set-up/install-k6/"
            exit 1
          fi

  run:
    desc: "[Dev] Run the service locally with hot reload"
    cmds:
      - go tool air -c .air.toml || go run {{.MAIN_PKG}}

  generate:
    desc: "[Dev] Run go generate (mocks, etc.)"
    cmds:
      - go generate ./...
      - go tool mockery

  # ─────────────────────────────────────────────────────────────
  # Build
  # ─────────────────────────────────────────────────────────────

  build:
    desc: "[Build] Build production binary with version info"
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}} {{.MAIN_PKG}}

  clean:
    desc: "[Build] Clean build artifacts"
    cmds:
      - rm -rf bin/
      - rm -f {{.COVERAGE_FILE}} coverage.html

  # ─────────────────────────────────────────────────────────────
  # Code Quality
  # ─────────────────────────────────────────────────────────────

  fmt:
    desc: "[Quality] Format all Go code"
    cmds:
      - go tool gofumpt -w .

  lint:
    desc: "[Quality] Run golangci-lint"
    cmds:
      - go tool golangci-lint run --timeout 5m ./...

  vuln:
    desc: "[Quality] Run govulncheck"
    cmds:
      - go tool govulncheck ./...

  # ─────────────────────────────────────────────────────────────
  # Testing
  # ─────────────────────────────────────────────────────────────

  test:
    desc: "[Test] Run unit tests (override format with TEST_FORMAT=dots|pkgname|standard-verbose)"
    cmds:
      - go tool gotestsum --format {{.TEST_FORMAT}} -- -race ./...

  test:integration:
    desc: "[Test] Run GoDog integration tests - smoke only (requires running service)"
    env:
      GODOG_TAGS: "@smoke && ~@requires-network"
    cmds:
      - go test -tags integration -v ./test/integration/...

  test:integration:all:
    desc: "[Test] Run all GoDog integration tests including network-dependent (requires running service)"
    cmds:
      - go test -tags integration -v ./test/integration/...

  test:e2e:
    desc: "[Test] Run full E2E test suite"
    cmds:
      - task: test
      - task: test:integration

  test:benchmark:
    desc: "[Test] Run Go benchmarks"
    cmds:
      - go test -bench=. -benchmem ./test/benchmark/...

  test:load:
    desc: "[Test] Run k6 load tests (requires running service)"
    preconditions:
      - sh: command -v k6
        msg: "k6 is not installed. Run 'task setup' or install manually: https://grafana.com/docs/k6/latest/set-up/install-k6/"
    cmds:
      - k6 run test/load/k6/health.js

  coverage:
    desc: "[Test] Generate test coverage report"
    cmds:
      - go tool gotestsum --format {{.TEST_FORMAT}} -- -race -coverprofile={{.COVERAGE_FILE}} -covermode=atomic ./...
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - go tool cover -func={{.COVERAGE_FILE}}

  # ─────────────────────────────────────────────────────────────
  # CI/CD
  # ─────────────────────────────────────────────────────────────

  ci:
    desc: "[CI] Run full CI pipeline locally"
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: coverage
      - task: vuln

  # ─────────────────────────────────────────────────────────────
  # Docker
  # ─────────────────────────────────────────────────────────────

  docker:build:
    desc: "[Docker] Build Docker image"
    cmds:
      - docker build -t {{.BINARY_NAME}}:{{.VERSION}} --build-arg VERSION={{.VERSION}} --build-arg GIT_COMMIT={{.GIT_COMMIT}} --build-arg BUILD_TIME={{.BUILD_TIME}} .

  docker:run:
    desc: "[Docker] Run Docker container locally"
    cmds:
      - docker run --rm -p 8080:8080 {{.BINARY_NAME}}:{{.VERSION}}

  # ─────────────────────────────────────────────────────────────
  # OpenAPI
  # ─────────────────────────────────────────────────────────────

  openapi:validate:
    desc: "[OpenAPI] Validate OpenAPI spec"
    cmds:
      - go tool vacuum lint -r .spectral.yaml api/openapi.yaml

  openapi:diff:
    desc: "[OpenAPI] Check for OpenAPI drift"
    cmds:
      - cmd: echo "TODO Implement OpenAPI drift detection"
