version: "3"

vars:
  BINARY_NAME: service
  MAIN_PKG: ./cmd/service
  COVERAGE_FILE: coverage.out
  TEST_FORMAT: testdox # default format, override with: task test TEST_FORMAT=dots
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  GIT_COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "unknown"
  BUILD_TIME:
    sh: date -u '+%Y-%m-%dT%H:%M:%SZ'
  LDFLAGS: -s -w -X main.Version={{.VERSION}} -X main.Commit={{.GIT_COMMIT}} -X main.BuildTime={{.BUILD_TIME}}
  IMAGE_NAME:
    sh: basename $(pwd)

tasks:
  default:
    desc: Show available tasks with descriptions
    silent: true
    cmds:
      - |
        # Colors (works in bash/zsh, degrades gracefully)
        BOLD='\033[1m'
        DIM='\033[2m'
        CYAN='\033[36m'
        GREEN='\033[32m'
        YELLOW='\033[33m'
        RESET='\033[0m'

        printf "${BOLD}Go Service Template Commands${RESET}\n"
        printf "\n"
        printf "${YELLOW}Setup:${RESET}\n"
        printf "  ${GREEN}task setup${RESET}                  Install all dev dependencies and git hooks\n"
        printf "  ${GREEN}task setup:k6${RESET}               Install k6 load testing tool\n"
        printf "\n"
        printf "${YELLOW}Development:${RESET}\n"
        printf "  ${GREEN}task run${RESET}                    Run service with hot reload (air)\n"
        printf "  ${GREEN}task generate${RESET}               Run go generate (mocks, etc.)\n"
        printf "  ${GREEN}task build${RESET}                  Build production binary\n"
        printf "  ${GREEN}task clean${RESET}                  Remove build artifacts\n"
        printf "\n"
        printf "${YELLOW}Code Quality:${RESET}\n"
        printf "  ${GREEN}task fmt${RESET}                    Format all Go code (gofumpt)\n"
        printf "  ${GREEN}task lint${RESET}                   Run golangci-lint\n"
        printf "  ${GREEN}task vuln${RESET}                   Run govulncheck for vulnerabilities\n"
        printf "  ${GREEN}task deadcode${RESET}               Find unreachable functions\n"
        printf "\n"
        printf "${YELLOW}Testing:${RESET}\n"
        printf "  ${GREEN}task test${RESET}                   Run unit tests with race detection\n"
        printf "  ${GREEN}task test:integration:smoke${RESET}  Run BDD integration tests (smoke only)\n"
        printf "  ${GREEN}task test:integration:all${RESET}   Run all BDD integration tests\n"
        printf "  ${GREEN}task test:integration:report${RESET} Generate JSON integration report\n"
        printf "  ${GREEN}task test:benchmark${RESET}         Run Go benchmarks\n"
        printf "  ${GREEN}task test:benchmark:save${RESET}    Save benchmark results for comparison\n"
        printf "  ${GREEN}task test:benchmark:compare${RESET}  Compare two benchmark runs (benchstat)\n"
        printf "  ${GREEN}task profile:cpu${RESET}             CPU profile via benchmarks\n"
        printf "  ${GREEN}task profile:mem${RESET}             Memory profile via benchmarks\n"
        printf "  ${GREEN}task test:load${RESET}              Run k6 load tests\n"
        printf "  ${GREEN}task test:e2e${RESET}               Run full E2E suite\n"
        printf "  ${GREEN}task coverage${RESET}               Generate test coverage report\n"
        printf "  ${GREEN}task coverage:report${RESET}        Generate rich coverage report (octocov)\n"
        printf "  ${GREEN}task coverage:view${RESET}          Generate coverage HTML and open in browser\n"
        printf "\n"
        printf "${YELLOW}Docker:${RESET}\n"
        printf "  ${GREEN}task docker:build${RESET}           Build Docker image\n"
        printf "  ${GREEN}task docker:run${RESET}             Run container locally\n"
        printf "  ${GREEN}task docker:clean${RESET}           Remove local Docker images\n"
        printf "\n"
        printf "${YELLOW}OpenAPI:${RESET}\n"
        printf "  ${GREEN}task openapi:validate${RESET}       Validate OpenAPI spec (Spectral)\n"
        printf "  ${GREEN}task openapi:diff${RESET}           Check for breaking changes vs main\n"
        printf "  ${GREEN}task openapi:changelog${RESET}      Generate changelog vs main\n"
        printf "\n"
        printf "${YELLOW}Analysis:${RESET}\n"
        printf "  ${GREEN}task docs${RESET}                   Start local documentation server\n"
        printf "  ${GREEN}task deps:graph${RESET}             Visualize module dependency graph\n"
        printf "\n"
        printf "${YELLOW}CI/CD:${RESET}\n"
        printf "  ${GREEN}task ci${RESET}                     Run full CI pipeline locally\n"
        printf "\n"
        printf "${YELLOW}Workflow Shortcuts:${RESET}\n"
        printf "  ${GREEN}task deps${RESET}                   Tidy, download, and verify dependencies\n"
        printf "  ${GREEN}task deps:update${RESET}            Update all dependencies to latest\n"
        printf "  ${GREEN}task check${RESET}                  Run all quality checks (fmt+lint+vuln)\n"
        printf "  ${GREEN}task verify${RESET}                 Full verification (deps+check+test)\n"
        printf "  ${GREEN}task dev:setup${RESET}              Set up development environment\n"
        printf "  ${GREEN}task quick${RESET}                  Quick check (format and test)\n"
        printf "\n"
        printf "${CYAN}Options:${RESET}\n"
        printf "  ${DIM}TEST_FORMAT=dots${RESET}              Change test output (dots|pkgname|standard-verbose)\n"
        printf "  ${DIM}BASE_REF=origin/develop${RESET}       Override OpenAPI diff base branch\n"
        printf "  ${DIM}HOST_PORT=9090${RESET}                Override docker:run host port (default: 8080)\n"
        printf "  ${DIM}BENCH_COUNT=20${RESET}                Override benchmark iteration count (default: 10)\n"
        printf "  ${DIM}BENCH_FILE=before.out${RESET}         Override benchmark output file (default: benchmark.out)\n"
        printf "  ${DIM}PPROF_PORT=9090${RESET}               Override pprof web UI port (default: 8081)\n"
        printf "  ${DIM}DOCS_PORT=8080${RESET}                Override pkgsite docs port (default: 6060)\n"
        printf "\n"
        printf "${CYAN}Examples:${RESET}\n"
        printf "  ${DIM}task run${RESET}                      Start dev server with hot reload\n"
        printf "  ${DIM}task test TEST_FORMAT=dots${RESET}    Run tests with minimal output\n"
        printf "  ${DIM}task ci${RESET}                       Run full CI checks locally\n"

  # ─────────────────────────────────────────────────────────────
  # Setup & Development
  # ─────────────────────────────────────────────────────────────

  setup:
    desc: Install all development dependencies
    cmds:
      - go mod download
      - go tool lefthook install
      - task: setup:k6
      - echo "Setup complete. All tools available via 'go tool'. Git hooks installed."

  setup:k6:
    desc: Install k6 load testing tool
    status:
      - command -v k6
    cmds:
      - cmd: |
          if command -v brew &> /dev/null; then
            brew install k6
          elif command -v apt-get &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y k6
          elif command -v choco &> /dev/null; then
            choco install k6
          else
            echo "Please install k6 manually: https://grafana.com/docs/k6/latest/set-up/install-k6/"
            exit 1
          fi

  run:
    desc: Run the service locally with hot reload
    cmds:
      - go tool air -c .air.toml || go run {{.MAIN_PKG}}

  generate:
    desc: Run go generate (mocks, etc.)
    cmds:
      - go generate ./...
      - go tool mockery

  # ─────────────────────────────────────────────────────────────
  # Build
  # ─────────────────────────────────────────────────────────────

  build:
    desc: Build production binary with version info
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o bin/{{.BINARY_NAME}} {{.MAIN_PKG}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -f {{.COVERAGE_FILE}} coverage.html
      - rm -f cpu.prof mem.prof benchmark.out deps.svg

  # ─────────────────────────────────────────────────────────────
  # Code Quality
  # ─────────────────────────────────────────────────────────────

  fmt:
    desc: Format all Go code
    cmds:
      - go tool gofumpt -w .

  lint:
    desc: Run golangci-lint
    cmds:
      - go tool golangci-lint run --timeout 5m ./...

  vuln:
    desc: Run govulncheck
    cmds:
      - go tool govulncheck ./...

  deadcode:
    desc: Find unreachable functions
    cmds:
      - go tool deadcode ./...

  # ─────────────────────────────────────────────────────────────
  # Testing
  # ─────────────────────────────────────────────────────────────

  test:
    desc: Run unit tests with race detection
    cmds:
      - go tool gotestsum --format {{.TEST_FORMAT}} -- -race ./...

  test:integration:smoke:
    desc: Run GoDog integration tests (smoke only, @smoke && ~@requires-network)
    env:
      GODOG_TAGS: "@smoke && ~@requires-network"
    cmds:
      - go test -tags integration -v ./test/integration/...

  test:integration:all:
    desc: Run all GoDog integration tests (no tag filtering)
    cmds:
      - go test -tags integration -v ./test/integration/...

  test:integration:report:
    desc: Run GoDog integration tests with JSON report
    env:
      GODOG_FORMAT: cucumber
      GODOG_OUTPUT_FILE: test/reports/integration.json
      GODOG_TAGS: "@smoke && ~@requires-network"
    cmds:
      - mkdir -p test/reports
      - go test -tags integration -v ./test/integration/...
      - echo "Report generated at test/reports/integration.json"

  test:integration:html:
    desc: Run GoDog integration tests with HTML report
    env:
      GODOG_FORMAT: cucumber
      GODOG_OUTPUT_FILE: test/reports/integration.json
      GODOG_TAGS: "@smoke && ~@requires-network"
    cmds:
      - mkdir -p test/reports
      - go test -tags integration -v ./test/integration/...
      - cmd: |
          if command -v npx &> /dev/null; then
            npx cucumber-html-reporter --input test/reports/integration.json --output test/reports/integration.html 2>/dev/null || echo "Install cucumber-html-reporter: npm install -g cucumber-html-reporter"
          else
            echo "JSON report at test/reports/integration.json (install npx for HTML)"
          fi
        silent: true

  test:e2e:
    desc: Run full E2E test suite
    cmds:
      - task: test
      - task: test:integration:smoke

  test:benchmark:
    desc: Run Go benchmarks
    cmds:
      - go test -bench=. -benchmem ./test/benchmark/...

  test:benchmark:save:
    desc: Run benchmarks and save results to file
    vars:
      BENCH_COUNT: '{{.BENCH_COUNT | default "10"}}'
      BENCH_FILE: '{{.BENCH_FILE | default "benchmark.out"}}'
    cmds:
      - go test -bench=. -benchmem -count={{.BENCH_COUNT}} ./test/benchmark/... | tee {{.BENCH_FILE}}

  test:benchmark:compare:
    desc: "Compare two benchmark runs (usage: task test:benchmark:compare -- old.out new.out)"
    preconditions:
      - sh: |
          set -- {{.CLI_ARGS}}
          [ "$#" -eq 2 ]
        msg: "Usage: task test:benchmark:compare -- old.out new.out"
    cmds:
      - go tool benchstat {{.CLI_ARGS}}

  profile:cpu:
    desc: Run benchmarks with CPU profiling
    vars:
      PPROF_PORT: '{{.PPROF_PORT | default "8081"}}'
    cmds:
      - go test -bench=. -cpuprofile=cpu.prof -benchmem ./test/benchmark/...
      - cmd: 'echo "View profile: go tool pprof -http=:{{.PPROF_PORT}} cpu.prof"'

  profile:mem:
    desc: Run benchmarks with memory profiling
    vars:
      PPROF_PORT: '{{.PPROF_PORT | default "8081"}}'
    cmds:
      - go test -bench=. -memprofile=mem.prof -benchmem ./test/benchmark/...
      - cmd: 'echo "View profile: go tool pprof -http=:{{.PPROF_PORT}} mem.prof"'

  test:load:
    desc: Run k6 load tests (requires running service)
    preconditions:
      - sh: command -v k6
        msg: "k6 is not installed. Run 'task setup' or install manually."
    cmds:
      - k6 run test/load/k6/health.js

  coverage:
    desc: Generate test coverage report
    cmds:
      - go tool gotestsum --format {{.TEST_FORMAT}} -- -race -coverprofile={{.COVERAGE_FILE}} -covermode=atomic ./...
      - cmd: grep -v -E '/mocks/|cmd/service|platform/telemetry' {{.COVERAGE_FILE}} > {{.COVERAGE_FILE}}.tmp && mv {{.COVERAGE_FILE}}.tmp {{.COVERAGE_FILE}}
        silent: true
      - go tool cover -func={{.COVERAGE_FILE}}

  coverage:report:
    desc: Generate coverage report with octocov
    deps: [coverage]
    cmds:
      - go tool octocov --config .octocov.yml

  coverage:view:
    desc: Generate coverage HTML and open in browser
    deps: [coverage]
    cmds:
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - cmd: |
          {{if eq OS "darwin"}}open coverage.html
          {{else if eq OS "windows"}}start coverage.html
          {{else}}xdg-open coverage.html 2>/dev/null || echo "Open coverage.html manually"{{end}}
        silent: true

  # ─────────────────────────────────────────────────────────────
  # Analysis
  # ─────────────────────────────────────────────────────────────

  docs:
    desc: Start local documentation server (pkgsite)
    vars:
      DOCS_PORT: '{{.DOCS_PORT | default "6060"}}'
    cmds:
      - cmd: 'echo "Serving docs at http://localhost:{{.DOCS_PORT}}"'
      - go tool pkgsite -http=:{{.DOCS_PORT}}

  deps:graph:
    desc: Visualize module dependency graph (requires graphviz)
    preconditions:
      - sh: command -v dot
        msg: "Graphviz is required. Install: brew install graphviz / apt install graphviz"
    cmds:
      - go mod graph | go tool modgraphviz | dot -Tsvg -o deps.svg
      - echo "Dependency graph saved to deps.svg"

  # ─────────────────────────────────────────────────────────────
  # CI/CD
  # ─────────────────────────────────────────────────────────────

  ci:
    desc: Run full CI pipeline locally
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: coverage
      - task: vuln

  # ─────────────────────────────────────────────────────────────
  # Workflow Shortcuts
  # ─────────────────────────────────────────────────────────────

  deps:
    desc: Tidy, download, and verify dependencies
    cmds:
      - go mod tidy
      - go mod download
      - go mod verify

  deps:update:
    desc: Update all dependencies to latest versions
    cmds:
      - go get -u ./...
      - task: deps

  check:
    desc: Run all code quality checks (fmt, lint, vuln)
    cmds:
      - task: fmt
      - task: lint
      - task: vuln

  verify:
    desc: Full verification (deps, quality checks, tests)
    cmds:
      - task: deps
      - task: check
      - task: test

  dev:setup:
    desc: Set up development environment
    cmds:
      - task: deps
      - task: setup
      - task: generate

  quick:
    desc: Quick check (format and test)
    cmds:
      - task: fmt
      - task: test

  # ─────────────────────────────────────────────────────────────
  # Docker
  # ─────────────────────────────────────────────────────────────

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.GIT_COMMIT}} --build-arg VERSION={{.VERSION}} --build-arg GIT_COMMIT={{.GIT_COMMIT}} --build-arg BUILD_TIME={{.BUILD_TIME}} .

  docker:run:
    desc: Run Docker container locally
    vars:
      HOST_PORT: '{{.HOST_PORT | default "8080"}}'
    cmds:
      - docker run --rm -p {{.HOST_PORT}}:8080 {{.IMAGE_NAME}}:{{.GIT_COMMIT}}

  docker:clean:
    desc: Remove local Docker images for this project
    cmds:
      - docker images {{.IMAGE_NAME}} -q | xargs -r docker rmi -f

  # ─────────────────────────────────────────────────────────────
  # OpenAPI
  # ─────────────────────────────────────────────────────────────

  openapi:validate:
    desc: Validate OpenAPI spec
    cmds:
      - go tool vacuum lint -r .spectral.yaml api/openapi.yaml

  openapi:diff:
    desc: Check for breaking changes vs main branch
    vars:
      BASE_REF: '{{.BASE_REF | default "origin/main"}}'
    cmds:
      - cmd: |
          BASELINE=$(mktemp)
          trap "rm -f $BASELINE" EXIT
          if git show {{.BASE_REF}}:api/openapi.yaml > "$BASELINE" 2>/dev/null; then
            echo "Comparing api/openapi.yaml against {{.BASE_REF}}..."
            go tool oasdiff breaking "$BASELINE" api/openapi.yaml && echo "No breaking changes detected."
          else
            echo "Baseline not found in {{.BASE_REF}}, skipping diff."
          fi

  openapi:changelog:
    desc: Generate changelog vs main branch
    vars:
      BASE_REF: '{{.BASE_REF | default "origin/main"}}'
    cmds:
      - cmd: |
          BASELINE=$(mktemp)
          trap "rm -f $BASELINE" EXIT
          if git show {{.BASE_REF}}:api/openapi.yaml > "$BASELINE" 2>/dev/null; then
            go tool oasdiff changelog "$BASELINE" api/openapi.yaml
          else
            echo "Baseline not found in {{.BASE_REF}}"
          fi
